# Generated by Django 5.1.6 on 2025-02-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Student',
        ),
    ]
