# Generated by Django 4.2 on 2026-05-05 03:37

from django.db import migrations, models
import mainpage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_eventrsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment. Max 10 MB.', null=True, upload_to='events/files/', validators=[mainpage.validators.validate_shared_attachment]),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment. Max 10 MB.', null=True, upload_to='messages/files/', validators=[mainpage.validators.validate_shared_attachment]),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
